version: '3.9'
services:
  api-excel-merge-tool:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MAIN_PKG: .           
    image: excel-merge-tool:latest
    env_file:
      - .env    
    restart: always   
    environment:
      - SERVER_PORT=8090
    healthcheck:    
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8090/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks : 
      - excel-merge-tool-network
  nginx-excel-merge-tool:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api-excel-merge-tool
    ports:
      - "8090:8090"
    restart: always
    networks:
      - excel-merge-tool-network

networks:
  excel-merge-tool-network:
    driver: bridge